import React from 'react';
import type { ReportHistoryItem } from '../../types/reports';
import { Download, Eye, RefreshCw, Clock, CheckCircle2, Sparkles } from 'lucide-react';

interface Props {
  history: ReportHistoryItem[];
  latestNewReportId?: string | null;
  onPreview: (reportId: string) => void;
  onDownload: (reportId: string, format: 'pdf' | 'csv') => void;
  onRegenerate: (reportId: string) => void;
}

export const ReportHistoryTable: React.FC<Props> = ({
  history,
  latestNewReportId,
  onPreview,
  onDownload,
  onRegenerate
}) => {
  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-xs space-y-4">
      <div className="flex items-center justify-between border-b border-slate-200 pb-3">
        <h3 className="text-xs font-extrabold text-[#0F2C59] tracking-tight flex items-center gap-2">
          <Clock className="w-4 h-4 text-[#0F2C59]" />
          <span>Generated Report History & Audit Archives ({history.length} Records)</span>
        </h3>
        <span className="text-[10px] font-mono font-bold text-slate-600">
          Role Filter Active
        </span>
      </div>

      {history.length === 0 ? (
        <div className="p-8 text-center text-xs text-slate-500 font-mono bg-slate-50 rounded-xl border border-slate-200 font-medium">
          No generated report artifacts found for current role access level.
        </div>
      ) : (
        <div className="border border-slate-200 rounded-xl overflow-hidden bg-white shadow-2xs">
          <table className="w-full text-left font-mono text-xs">
            <thead className="bg-slate-100 text-slate-700 border-b border-slate-200 text-[11px] font-extrabold">
              <tr>
                <th className="p-3.5">Report ID</th>
                <th className="p-3.5">Report Title</th>
                <th className="p-3.5">Target Well</th>
                <th className="p-3.5">Generated By</th>
                <th className="p-3.5">Generated At</th>
                <th className="p-3.5">Status</th>
                <th className="p-3.5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-900 font-medium">
              {history.map((item) => {
                const isNew = latestNewReportId
                  ? item.report_id === latestNewReportId
                  : false;
                return (
                  <tr key={item.report_id} className={`transition-colors ${isNew ? 'bg-emerald-50/40 hover:bg-emerald-50/70' : 'hover:bg-slate-50'}`}>
                    <td className="p-3.5 font-bold text-[#0F2C59]">{item.report_id}</td>
                    <td className="p-3.5 font-extrabold text-slate-900">
                      <div className="flex items-center gap-2">
                        <span>{item.title}</span>
                        {isNew && (
                          <span className="px-2 py-0.5 rounded-full bg-emerald-600 text-white font-black text-[9px] font-mono tracking-wider flex items-center gap-1 shadow-2xs animate-pulse shrink-0">
                            <Sparkles className="w-2.5 h-2.5 text-amber-300 fill-amber-300" />
                            NEW
                          </span>
                        )}
                      </div>
                    </td>
                  <td className="p-3.5 text-slate-800 font-semibold">
                    {item.well_name} <span className="text-slate-500 text-[10px]">({item.well_id})</span>
                  </td>
                  <td className="p-3.5 text-slate-700 font-medium">
                    {item.generated_by} <span className="text-slate-500 text-[10px]">({item.user_role})</span>
                  </td>
                  <td className="p-3.5 text-slate-600 text-[11px] font-medium">
                    {new Date(item.generated_at).toLocaleString()}
                  </td>
                  <td className="p-3.5">
                    <span className="px-2.5 py-1 rounded-md bg-emerald-50 border border-emerald-300 text-emerald-900 text-[10px] font-bold flex items-center gap-1 w-fit shadow-2xs">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700" />
                      {item.status}
                    </span>
                  </td>
                  <td className="p-3.5 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button
                        onClick={() => onPreview(item.report_id)}
                        title="Preview Report"
                        className="p-1.5 bg-slate-100 hover:bg-slate-200 text-[#0F2C59] border border-slate-300 rounded-md transition-colors"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </button>

                      <button
                        onClick={() => onDownload(item.report_id, 'pdf')}
                        title="Download PDF"
                        className="px-3 py-1 bg-rose-50 hover:bg-rose-100 text-rose-800 border border-rose-300 rounded text-[10px] font-extrabold transition-colors flex items-center gap-1 shadow-2xs"
                      >
                        <Download className="w-3 h-3 text-rose-700" />
                        <span>PDF Report</span>
                      </button>

                      <button
                        onClick={() => onRegenerate(item.report_id)}
                        title="Regenerate Artifact"
                        className="p-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 border border-slate-300 rounded transition-colors"
                      >
                        <RefreshCw className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
